## Usage: ansible-playbook -i $HOST, Scripts/BAZEL.yaml -e bazel_version="0.19.1" --ask-become --ask-pass

- name: Download and Install bazel
  hosts: all
  gather_facts: False
  become: True

  vars:
    bazel_version: "0.19.1"

  tasks:
    # https://github.com/bazelbuild/bazel/releases/download/{{ bazel_version }}/bazel-{{ bazel_version }}-installer-linux-x86_64.sh
    # https://github.com/bazelbuild/bazel/releases/download/0.21.0/bazel_0.21.0-linux-x86_64.deb
    # https://github.com/bazelbuild/bazel/releases/download/0.19.1/bazel_0.19.1-linux-x86_64.deb
    - name: Copy bazel_{{ bazel_version }}
      copy:
        src: "../src/bazel_{{ bazel_version }}-linux-x86_64.deb"
        dest: "/tmp/"

    - name: Fix dependencies for bazel 0.19.1
      shell: "apt install -y openjdk-8-jdk || apt --fix-broken install -y "
      when: "'0.19.1' in bazel_version"

    - name: Install bazel_{{ bazel_version }}
      apt:
        deb: "/tmp/bazel_{{ bazel_version }}-linux-x86_64.deb"
