## Usage: ansible-playbook -i $HOST, Scripts/Install.yaml --ask-become --ask-pass
### ATTENTION ###
## The system will REBOOT at the end ##

- name: Install Prerequirements for Deepspeech and Tensorflow
  hosts: all
  gather_facts: False
  become: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        upgrade: "yes"
        update_cache: "yes"

    - name: Install Softwares
      apt:
        pkg:
          - unzip
          - build-essential
          - libboost-all-dev
          - cmake
          - zlib1g-dev
          - libbz2-dev
          - liblzma-dev
          - libsox-dev
          - python3-pip
          - python3-numpy
          - pkg-config
          - zip
          - g++
          - python
          - libpython2.7-dev
          - python-numpy
          - python-wheel
          - python-pip
          - libpcre3
          # - libpcre3–dev # Not Available on Ubuntu 18.04, but it works with Ubuntu 16.04
          - python-pexpect
          - python-dev
          - python3-dev
          - python3.6-dev
          - libeigen3-dev
          - git-lfs

    - name: Clean APT
      apt:
        autoclean: "yes"
        autoremove: "yes"

    - name: Add Python 3.6 repository
      apt_repository:
        repo: ppa:deadsnakes/ppa

    - name: Install python3.6
      apt:
        update_cache: yes
        name: python3.6

    - name: upgrade pip to python3.6
      shell: "curl https://bootstrap.pypa.io/get-pip.py | python3.6"

    - name: Upgrade pip3/pip to latest
      shell: |
        pip3 install --upgrade pip
        python -m pip install --upgrade pip setuptools

    - name: Install pexpect for python3
      shell: "pip3 install pexpect"

    - name: Download NodeJS 10.x repository
      shell: "curl -sL https://deb.nodesource.com/setup_10.x | bash -"

    - name: Install NodeJS 10.x
      apt:
        name: nodejs

    - name: Install node-pre-gyp with NPM
      shell: "npm install -g node-pre-gyp"

    - name: Update git lfs
      shell: "git lfs install"

    - name: Reboot after the installation
      reboot:
        reboot_timeout: 300
