- name: Install Deepspeech v0.5.1
  hosts: all
  gather_facts: False
  become: true

  vars:
    tensorflow_version: "r1.13"
    DeepSpeech_version: "tags/v0.5.1"
    bazel_version: "0.19.1"

- import_playbook: Install.yaml
- import_playbook: SOX.yaml
- import_playbook: KENLM.yaml
- import_playbook: SWIG.yaml
- import_playbook: BAZEL.yaml
- import_playbook: DEEPSPEECH.yaml
- import_playbook: TENSORFLOW.yaml
- import_playbook: TS_DEEPSPEECH.yaml
## (Optional/depends your system) ##
# - import_playbook: FIX_TENSORFLOW.yaml
- import_playbook: Test.yaml
