## Usage: ansible-playbook -i $HOST, Scripts/TENSORFLOW.yaml -e tensorflow_version="r1.13" --ask-become --ask-pass

- name: Clone Tensorflow and Build
  hosts: all
  gather_facts: False
  become: True

  vars:
    tensorflow_version: "r1.13"

  tasks:
    - name: Clone Mozilla/Tensorflow and Checkout to {{ tensorflow_version }}
      git:
        repo: "https://github.com/mozilla/tensorflow.git"
        dest: /srv/tensorflow
        version: "{{ tensorflow_version }}"

    - name: Clean old bazel build
      shell: "bazel clean --async"
      args:
        chdir: "/srv/tensorflow"

    - include_tasks: answer_tensorflow.yaml

    - name: Build with bazel, Deepspeech for tensorflow `r1.13`
      shell: |
        ln -s /srv/DeepSpeech/native_client ./
        bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie
      args:
        chdir: "/srv/tensorflow"
      when: "'r1.13' in tensorflow_version"

    ## Generate_trie has been removed for version 0.7.0-alpha3 in deepspeech
    - name: Build with bazel, Deepspeech for tensorflow `r1.15`
      shell: |
        ln -s /srv/DeepSpeech/native_client ./
        bazel build --workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so
      args:
        chdir: "/srv/tensorflow"
      when: "'r1.15' in tensorflow_version"

    - pause:
        seconds: 30

    ## Reconfigure, I had some issues and it seems to be ok after doing that.
    - include_tasks: answer_tensorflow.yaml

    - name: Build Tensorflow `build_pip_package`
      shell: "bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package"
      args:
        chdir: "/srv/tensorflow"

    - name: Create /tmp/tensorflow/tensorflow-*.whl
      shell: "./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow"
      args:
        chdir: "/srv/tensorflow"

    - name: Remove default Tensorflow version and Install built version
      shell: |
        pip3 uninstall -y tensorflow
        pip3 install /tmp/tensorflow/*.whl
